version: '3'
services:
  app:
    build: ./app

    container_name: app

    #environment:
    restart: on-failure

    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    command: python app.py
